---
AllCops:
  TargetRubyVersion: 3

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
